name: hprofile Actions
on: workflow_dispatch
env:
  AWS_REGION: ap-southeast-1
jobs:
  Testing:
      runs-on: ubuntu-latest
      steps:
        - name: Testing workflow
          run: echo "Workflow works!"
          
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Maven Test
          run: mvn test

        - name: Checkstyle
          run: mvn checkstyle:checkstyle
          
  Build_Publish:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and upload image to ECR  
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.aws_access_key_id }}
          secret_key: ${{ secrets.aws_secret_access_key }}
          registry: ${{ secrets.registry }}
          cache_from: ${{ secrets.cache }}
          tags: "latest,${{ github.run_number }}"
          repo: actionsapp
          region: ${{ env.AWS_REGION }}
          auto_tag: true
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./

        
  
  
